<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';

function render_admin_page(): never {
    $user = current_user();
    $isAdmin = $user && $user['role'] === 'admin';
    ?><!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Администрирование — StudentHub KZ</title>
<style>body{margin:0;background:#090810;color:#f6f4ff;font:16px/1.5 Arial,sans-serif}.wrap{max-width:1000px;margin:auto;padding:42px 22px}a{color:#8fdfff}.muted{color:#aaa6b9}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{border:1px solid #373049;border-radius:14px;padding:18px;background:#12111d}input,textarea,select{width:100%;box-sizing:border-box;background:#0d0c15;color:#fff;border:1px solid #3b354f;border-radius:8px;padding:10px}label{display:grid;gap:5px;margin:10px 0;color:#ccc6dd}button{border:0;border-radius:9px;background:#8568ec;color:#fff;font-weight:bold;padding:11px 14px;cursor:pointer}.row{display:flex;gap:10px;align-items:center;justify-content:space-between}.hidden{display:none}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head>
<body><main class="wrap"><div class="row"><a href="/">← StudentHub KZ</a><span class="muted"><?= $user ? escape_html($user['email']) : 'Гость' ?></span></div>
<p class="muted">ДОСТУП ПО РОЛИ</p><h1>Администрирование каталога</h1>
<?php if (!$isAdmin): ?><div class="card"><p>Доступ есть только у администратора.</p><p class="muted">Войдите с email, указанным в <code>ADMIN_EMAILS</code> в файле <code>openserver/.env</code>.</p></div>
<?php else: ?><div class="grid"><section class="card"><h2>Каталог</h2><div id="catalog">Загрузка…</div></section><section class="card"><div class="row"><h2 id="title">Новый университет</h2><button id="changeType" type="button">Грант</button></div><form id="editor"></form><p id="status" class="muted"></p></section></div>
<script>
const state={type:'university',item:null};const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opts){const r=await fetch(url,opts);const data=await r.json();if(!r.ok)throw Error(data.error||'Ошибка');return data}
function fields(){const x=state.item||{};const common=`<label>Slug<input name="slug" required value="${esc(x.slug||'')}"></label><label>Источник HTTPS<input name="sourceUrl" required value="${esc(x.source_url||'')}"></label><label>Дата проверки<input name="checkedAt" type="date" required value="${esc(x.checked_at||new Date().toISOString().slice(0,10))}"></label>`;$('#title').textContent=(x.id?'Редактировать: ':'Новый ')+(state.type==='university'?'университет':'грант');$('#editor').innerHTML=state.type==='university'?`<label>Название<input name="name" required value="${esc(x.name||'')}"></label><label>Город<input name="city" required value="${esc(x.city||'')}"></label><label>Тип<input name="kind" value="${esc(x.type||'')}"></label><label>Сайт HTTPS<input name="websiteUrl" value="${esc(x.website_url||'')}"></label><label>Описание<textarea name="description" required>${esc(x.description||'')}</textarea></label>${common}<button>Сохранить</button>`:`<label>Название<input name="title" required value="${esc(x.title||'')}"></label><label>Организация<input name="providerName" required value="${esc(x.provider_name||'')}"></label><label>Город<input name="city" value="${esc(x.city||'')}"></label><label>Направление<input name="specialty" value="${esc(x.specialty||'')}"></label><label>Финансирование<input name="amountDescription" value="${esc(x.amount_description||'')}"></label><label>Условия<textarea name="eligibility" required>${esc(x.eligibility||'')}</textarea></label><label>Дедлайн<input name="deadline" type="date" required value="${esc(x.deadline||'')}"></label><label>Ссылка на заявку HTTPS<input name="applicationUrl" value="${esc(x.application_url||'')}"></label>${common}<button>Сохранить</button>`;$('#editor').onsubmit=save}
async function load(){const data=await api('/api/admin/catalog');$('#catalog').innerHTML=['universities','grants'].map(key=>`<h3>${key==='universities'?'Университеты':'Гранты'}</h3>${data[key].length?data[key].map(x=>`<p><button data-type="${key==='universities'?'university':'grant'}" data-id="${x.id}">${esc(x.name||x.title)}</button></p>`).join(''):'<p class="muted">Записей нет.</p>'}`).join('');$('#catalog').querySelectorAll('button').forEach(button=>button.onclick=()=>{state.type=button.dataset.type;state.item=data[state.type==='university'?'universities':'grants'].find(x=>x.id==button.dataset.id);fields()})}
async function save(event){event.preventDefault();const body=Object.fromEntries(new FormData(event.target));if(state.item)body.id=state.item.id;try{await api('/api/admin/'+state.type,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('#status').textContent='Сохранено.';state.item=null;await load();fields()}catch(e){$('#status').textContent=e.message}}
$('#changeType').onclick=()=>{state.type=state.type==='university'?'grant':'university';state.item=null;$('#changeType').textContent=state.type==='university'?'Грант':'Университет';fields()};load().then(fields).catch(e=>$('#catalog').textContent=e.message);
</script><?php endif; ?></main></body></html><?php
    exit;
}
